# Generated by Django 2.1.4 on 2018-12-24 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='titile',
            new_name='title',
        ),
    ]
